import { ChatHeader } from "../components/chat/ChatHeader";
import { EmptyChatScreen } from "../components/chat/EmptyChatScreen";
import { ChatInput } from "../components/chat/ChatInput";
import { useState, useEffect } from "react";
import ChatSidebar from "@/components/chat/ChatSidebar";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: Date;
}

interface Conversation {
  id: string;
  title: string;
  messages: Message[];
  createdAt: Date;
}

export interface ChatSidebarProps {
  conversations: Conversation[];
  currentConversationId: string | null;
  onNewChat: () => void;
  onSelectConversation: (id: string) => void;
  onDeleteConversation: (id: string) => void;
  onCollapse: () => void;
  isCollapsed: boolean;
}

export default function ChatPage() {
  const [conversations, setConversations] = useState<Conversation[]>([]);
  const [currentConversationId, setCurrentConversationId] = useState<string | null>(null);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [showNewChat, setShowNewChat] = useState(false);

  // Get current conversation
  const currentConversation = conversations.find(c => c.id === currentConversationId);
  const currentMessages = currentConversation?.messages || [];

  const handleNewChat = () => {
    setCurrentConversationId(null);
    setShowNewChat(true);
  };

  const handleSendMessage = (message: string) => {
    setShowNewChat(false);
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: message,
      timestamp: new Date(),
    };

    // If no current conversation, create a new one
    if (!currentConversationId) {
      const newConversation: Conversation = {
        id: Date.now().toString(),
        title: message.length > 30 ? message.slice(0, 30) + "..." : message,
        messages: [userMessage],
        createdAt: new Date(),
      };
      
      setConversations(prev => [newConversation, ...prev]);
      setCurrentConversationId(newConversation.id);
    } else {
      // Update existing conversation
      setConversations(prev => 
        prev.map(conv => 
          conv.id === currentConversationId
            ? {
                ...conv,
                messages: [...conv.messages, userMessage],
                title: conv.messages.length === 0 
                  ? (message.length > 30 ? message.slice(0, 30) + "..." : message)
                  : conv.title
              }
            : conv
        )
      );
    }

    // Simulate AI response after a delay
    setTimeout(() => {
      const aiMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: `I understand you said: "${message}". This is a simulated AI response. In a real chatbot, this would be generated by an AI service.`,
        timestamp: new Date(),
      };

      setConversations(prev => 
        prev.map(conv => 
          conv.id === currentConversationId
            ? {
                ...conv,
                messages: [...conv.messages, aiMessage]
              }
            : conv
        )
      );
    }, 1000);
  };

  const handleSelectConversation = (id: string) => {
    setCurrentConversationId(id);
  };

  const handleDeleteConversation = (id: string) => {
    setConversations(prev => prev.filter(conv => conv.id !== id));
    
    if (currentConversationId === id) {
      setCurrentConversationId(null);
    }
  };

  const handleSidebarCollapse = () => {
    setSidebarCollapsed(!sidebarCollapsed);
  };

  return (
    <div className="flex flex-col h-screen bg-white text-gray-900">
      {/* Header */}
      <ChatHeader />

      {/* Main content: Sidebar + Chat */}
      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        
        <ChatSidebar 
          conversations={conversations}
          currentConversationId={currentConversationId}
          onNewChat={handleNewChat}
          onSelectConversation={handleSelectConversation}
          onDeleteConversation={handleDeleteConversation}
          onCollapse={handleSidebarCollapse}
          isCollapsed={sidebarCollapsed}
        />

        {/* Chat area */}
        <main className="flex-1 flex flex-col overflow-hidden">
          <div className="flex-1 flex flex-col overflow-y-auto">
            {/* Show EmptyChatScreen for new chat */}
            {showNewChat && (
              <div className="flex-1">
                <EmptyChatScreen onPromptClick={handleSendMessage} />
              </div>
            )}

            {/* Show previous conversations */}
            {!showNewChat && (
              <div className="flex-1 overflow-y-auto p-4">
                <div className="max-w-4xl mx-auto flex flex-col gap-4">
                  {currentMessages.length === 0 ? (
                    <EmptyChatScreen onPromptClick={handleSendMessage} />
                  ) : (
                    currentMessages.map((message) => (
                      <div
                        key={message.id}
                        className={`p-4 rounded-lg shadow-sm ${
                          message.role === "user" 
                            ? "bg-blue-600 text-white ml-12" 
                            : "bg-gray-50 mr-12"
                        }`}
                      >
                        <p className="text-xs opacity-60 mb-1 capitalize">
                          {message.role}
                        </p>
                        <p className="whitespace-pre-wrap">{message.content}</p>
                        <p className="text-xs opacity-60 mt-2">
                          {message.timestamp.toLocaleTimeString()}
                        </p>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}
          </div>

          {/* Input always visible at bottom */}
          <div className="border-t p-4">
            <ChatInput onSubmit={handleSendMessage} />
          </div>
        </main>
      </div>
    </div>
  );
}